[package]
name = "raves-on-rust"
version = "0.1.0"
edition = "2021"
description = "Placeholder. See https://github.com/D1plo1d/raves-on-rust"
license = "AGPL3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
